version: '3.8'

services:
  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - service-b
      - zipkin

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - WEATHER_API_KEY=82a06c268ded479ca51163545251407
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
    depends_on:
      - zipkin